### PR TITLE
Interactions are properly deleted

### PR DESCRIPTION
**Pull request by tdoshi**
- interactions are properly deleted, so once they're deleted, you can re-add if necessary

### CODE REVIEW

**Comment by ato1120** [comment]
Buggy - interactions don't load properly on refresh, are all deleted.

**Comment by tdoshi** [comment]
Fixed the problem, I think! let me know if things still don't work

**Comment by ato1120** [comment]
Fixed for handoffs, still having persistence problems with collaborations. 

Ex. Draw two events, add a collaboration, refresh, the collaboration doesn't render, but it is still in the data, can't draw a new interaction between the events.

**Comment by ato1120** [comment]
Ah, it might just be the most recently drawn interaction AFTER a collaboration is drawn as well? Just replicated the bad reload for handoffs as well. I could keep looking into it, but basically, still buggy?

**Comment by ato1120** [comment]
Found the (hopefully) final problem!! 

The variable "intId" is used in awareness.js in drawInteraction to loop over first the "remainingHandoffs" and then the "remainingCollabs" which are found separately to delete old ones and redraw. "intId" was not re-initialized on the "remainingCollabs" loop and thus would delete a handoff. So on page load, a handoff would be missing.

**Comment by mgoulder** [comment]
Still buggy :((

Not sure I can exactly figure out what behavior causes the interactions/handoffs to not persist on reload, but here's what I've observed:
- MOST of the time, this only occurs on the very first handoff/interaction drawn.  But every once in a while I draw the first handoff/interaction and it does persist on reload.
- Whether or not you "save" the new event upon making it does NOT seem to affect the problem
- It doesn't have to be the first handoff OR collaboration drawn, it seems like it just has to be the first of its TYPE. 
- Whether the interacting events are fully overlapping or partially overlapping does NOT seem to affect the problem.

**Pull request merged**
