### PR TITLE
Show user name and remaining time to current user's task in the side bar.

### PR DESCRIPTION
**Pull request by negarrahmati**
renderChatbox() is responsible for getting the user name and calling the functions to track current users event.

### CODE REVIEW

**Comment by negarrahmati** [comment]
Also, changed the email from jayhp9@stanford.edu to stanfordhci.odesk@gmail.com

**Comment by jaypatelh** [comment]
Merged master into it.
Showing username works.
But showing remaining time does not work. Can you fix that and push a new commit to this pull request?

**Comment by negarrahmati** [comment]
Sure!
Will you let me know if you can do the popovers yourself?
Interviewing ODesk workers is taking me so long and I am not sure if I have
enough to fix it till Wednesday...

Negar

**Comment by negarrahmati** [comment]
Jay,
When I asked Tulsee to check why the remaining time doesn't show up, did she have access to the changes I had made in this pull request?
If yes, why is this pull request still in the list of pull requests?

**Comment by jaypatelh** [comment]
Hmm, can't remember..

Jay.

**Comment by negarrahmati** [comment]
Jay,

The sidebar is already working in this branch. I think you should merge this one since it also shows the user name.

**Comment by jaypatelh** [comment]
Merged! Pull from master, and test it once more to make sure it works!

**Comment by tdoshi** [comment]
Should I work on the delayed task problem, Negar, or is that already solved?

On Wed, Apr 2, 2014 at 11:55 PM, Jay Patel notifications@github.com wrote:

> Merged! Pull from master, and test it once more to make sure it works!
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/StanfordHCI/flash-startups/pull/100#issuecomment-39418329
> .

## 

Tulsee Doshi
B.S. Symbolic Systems - Stanford University Class of 2015

**Pull request merged**
