### PR TITLE
finished populating/updating DRI dropdown on event popover

### PR DESCRIPTION
**Pull request by dretelny**

### CODE REVIEW

**Comment by jaypatelh** [comment]
Hey Daniela, it seems like the DRI popover does not allow me to choose the first member in the side bar member list. Is that a bug?

**Comment by dretelny** [comment]
Interesting! That wasn’t happening before. Maybe it has something to do with the members? Do you want to push it and then I can try to figure it out? or should I fix it first? It was working on my local version that I pushed

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu
www.danielaretelny.com

**Comment by dretelny** [comment]
I actually think I might know what the issue is though. How do I fix it with regard to the pushing/pulling? I should probably merge the latest from master first, no? 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu
www.danielaretelny.com

**Comment by jaypatelh** [comment]
If you fix it and commit and push to your branch, the pull request will be
automatically updated.

Jay.

**Comment by jaypatelh** [comment]
Yes sure you can get the latest from master first. Then, once you fix it,
just commit and push to your branch.

Jay.

**Comment by dretelny** [comment]
Ok I think I just fixed it but I didn’t get the latest from master first…let me do that and then fix it and commit/push

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu
www.danielaretelny.com

**Comment by dretelny** [comment]
I think I submitted the request but am not sure if I did it right. Can you let me know if it went through and if it fixes the problem? Git is being a little finicky with me at the moment…Let me know as soon as you can since I want to make sure this gets pushed to master/heroku :) 

Thanks, Jay!

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu
www.danielaretelny.com

**Comment by jaypatelh** [comment]
Looks good Daniela. Merged it into master and deleted the branch. Create a new branch (off of master, after updating master) for any new feature you start working on next. Great job with your first merge! :+1:

**Comment by dretelny** [comment]
YAY!!! Glad to hear Foundry didn’t explode when I merged :) thanks so much, Jay! 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu
www.danielaretelny.com

**Pull request merged**
